# Generated by Django 2.0.4 on 2018-04-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_folioimage_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folioimage',
            name='index',
        ),
        migrations.AddField(
            model_name='index',
            name='category_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='index',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='background_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='FolioImage',
        ),
    ]
