# Generated by Django 2.0.4 on 2018-04-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180429_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='index',
            name='category_image',
        ),
        migrations.AlterField(
            model_name='index',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='folioimage',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Index'),
        ),
    ]
